#######################################################################################################################
# 
# Samarth's Kitty Configration
#
#######################################################################################################################

# themes
include GruvBox_DarkHard.conf
#include Wryan.conf
#include VSCode_Dark.conf

# terminal opacity and blur
background_opacity 0
background_blur 0

# advance 
term xterm-kitty

# terminal bell
enable_audio_bell no

# font
font_family        JetBrains Mono Nerd Font
font_size 17.0

# url
url_style curly

# cursor customization
block / beam / underline
cursor_shape block
cursor_blink_interval 0
cursor_stop_blinking_after 0
shell_integration disabled

# scrollback
scrollbar_handle_opacity      0
scrollbar_track_opacity       0
scrollbar_track_hover_opacity 0
scrollback_lines              5000
wheel_scroll_multiplier       3.0

# mouse
mouse_hide_wait 5

# window layout
confirm_os_window_close 0
remember_window_size  	no
initial_window_width  	1200
initial_window_height 	750
window_border_width 	1.5pt
enabled_layouts 	tall
window_padding_width 	0
window_margin_width 	2
hide_window_decorations	 no

# tab management
map ctrl+shift+t new_tab
map ctrl+shift+right next_tab
map ctrl+shift+left previous_tab
map ctrl+shift+q close_tab

# Performance
sync_to_monitor no
